# Generated by Django 4.2.7 on 2023-11-28 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('time_log', models.TimeField(help_text='Enter the exact time!')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
